name: Lintage

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  flake8:
    name: Checking lint rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip3 install -c requirements.txt flake8

      - name: Flake8
        run: |
          flake8 download

          
